require:
  - standard
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "lib/templates/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
Rails:
  Enabled: true # enable rubocop-rails cops

RSpec:
  Enabled: true # enable rubocop-rspec cops

RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Style/FrozenStringLiteralComment:
  Enabled: true
  SafeAutoCorrect: true
