linters:
  ColorVariable:
    enabled: false
  QualifyingElement:
    enabled: false
  LeadingZero:
    enabled: false
  PropertySortOrder:
    enabled: false
  SelectorFormat:
    enabled: false
  StringQuotes:
    enabled: false
  IdSelector:
    enabled: false
  SingleLinePerSelector:
    enabled: false
  HexLength:
    enabled: false
