# frozen_string_literal: true

module Location
  def self.all
    [
      { code: "JHR01", zone: "Pulau Aur, Pemanggil", state: "Johor" },
      { code: "JHR02", zone: "Johor Bahru, Kota Tinggi, Mersing", state: "Johor" },
      { code: "JHR03", zone: "Kluang, Pontian", state: "Johor" },
      { code: "JHR04", zone: "Batu Pahat, Muar, Segamat, Gemas", state: "Johor" },
      { code: "KDH01", zone: "Kota Setar, Kubang Pasu, Pokok Sena (Daerah Kecil)", state: "Kedah" },
      { code: "KDH02", zone: "Kuala Muda, Yan, Pendang", state: "Kedah" },
      { code: "KDH03", zone: "Padang Terap, Sik", state: "Kedah" },
      { code: "KDH04", zone: "Baling", state: "Kedah" },
      { code: "KDH05", zone: "Bandar Bahru, Kulim", state: "Kedah" },
      { code: "KDH06", zone: "Langkawi", state: "Kedah" },
      { code: "KDH07", zone: "Puncak Gunung Jerai", state: "Kedah" },
      { code: "KTN01", zone: "Bachok, Kota Bharu, Pasir Puteh, Tumpat, Pasir Mas, Tanah Merah, Machang, Kuala Krai, Mukim Chiku", state: "Kelantan" },
      { code: "KTN02", zone: "Gua Musang (Daerah Galas Dan Bertam), Jeli, Jajahan Kecil Lojing", state: "Kelantan" },
      { code: "MLK01", zone: "Seluruh Negeri Melaka", state: "Melaka" },
      { code: "NGS01", zone: "Jempol, Tampin", state: "Negeri Sembilan" },
      { code: "NGS02", zone: "Jelebu, Kuala Pilah, Port Dickson, Rembau, Seremban", state: "Negeri Sembilan" },
      { code: "PHG01", zone: "Pulau Tioman", state: "Pahang" },
      { code: "PHG02", zone: "Kuantan, Pekan, Rompin, Muadzam Shah", state: "Pahang" },
      { code: "PHG03", zone: "Jerantut, Temerloh, Maran, Bera, Chenor, Jengka", state: "Pahang" },
      { code: "PHG04", zone: "Bentong, Lipis, Raub", state: "Pahang" },
      { code: "PHG05", zone: "Genting Sempah, Janda Baik, Bukit Tinggi", state: "Pahang" },
      { code: "PHG06", zone: "Cameron Highlands, Genting Higlands, Bukit Fraser", state: "Pahang" },
      { code: "PLS01", zone: "Kangar, Padang Besar, Arau", state: "Perlis" },
      { code: "PNG01", zone: "Seluruh Negeri Pulau Pinang", state: "Pulau Pinang" },
      { code: "PRK01", zone: "Tapah, Slim River, Tanjung Malim", state: "Perak" },
      { code: "PRK02", zone: "Kuala Kangsar, Sg. Siput , Ipoh, Batu Gajah, Kampar", state: "Perak" },
      { code: "PRK03", zone: "Lenggong, Pengkalan Hulu, Grik", state: "Perak" },
      { code: "PRK04", zone: "Temengor, Belum", state: "Perak" },
      { code: "PRK05", zone: "Kg Gajah, Teluk Intan, Bagan Datuk, Seri Iskandar, Beruas, Parit, Lumut, Sitiawan, Pulau Pangkor", state: "Perak" },
      { code: "PRK06", zone: "Selama, Taiping, Bagan Serai, Parit Buntar", state: "Perak" },
      { code: "PRK07", zone: "Bukit Larut", state: "Perak" },
      { code: "SBH01", zone: "Bahagian Sandakan (Timur), Bukit Garam, Semawang, Temanggong, Tambisan, Bandar Sandakan, Sukau", state: "Sabah" },
      { code: "SBH02", zone: "Beluran, Telupid, Pinangah, Terusan, Kuamut, Bahagian Sandakan (Barat)", state: "Sabah" },
      { code: "SBH03", zone: "Lahad Datu, Silabukan, Kunak, Sahabat, Semporna, Tungku, Bahagian Tawau (Timur)", state: "Sabah" },
      { code: "SBH04", zone: "Bandar Tawau, Balong, Merotai, Kalabakan, Bahagian Tawau (Barat) ", state: "Sabah" },
      { code: "SBH05", zone: "Kudat, Kota Marudu, Pitas, Pulau Banggi, Bahagian Kudat", state: "Sabah" },
      { code: "SBH06", zone: "Gunung Kinabalu", state: "Sabah" },
      { code: "SBH07", zone: "Kota Kinabalu, Ranau, Kota Belud, Tuaran, Penampang, Papar, Putatan, Bahagian Pantai Barat", state: "Sabah" },
      { code: "SBH08", zone: "Pensiangan, Keningau, Tambunan, Nabawan, Bahagian Pendalaman (Atas)", state: "Sabah" },
      { code: "SBH09", zone: "Beaufort, Kuala Penyu, Sipitang, Tenom, Long Pa Sia, Membakut, Weston, Bahagian Pendalaman (Bawah)", state: "Sabah" },
      { code: "SGR01", zone: "Gombak, Petaling, Sepang, Hulu Langat, Hulu Selangor, Shah Alam", state: "Selangor" },
      { code: "SGR02", zone: "Kuala Selangor, Sabak Bernam", state: "Selangor" },
      { code: "SGR03", zone: "Klang, Kuala Langat", state: "Selangor" },
      { code: "SWK01", zone: "Limbang, Lawas, Sundar, Trusan", state: "Sarawak" },
      { code: "SWK02", zone: "Miri, Niah, Bekenu, Sibuti, Marudi", state: "Sarawak" },
      { code: "SWK03", zone: "Pandan, Belaga, Suai, Tatau, Sebauh, Bintulu", state: "Sarawak" },
      { code: "SWK04", zone: "Sibu, Mukah, Dalat, Song, Igan, Oya, Balingian, Kanowit, Kapit", state: "Sarawak" },
      { code: "SWK05", zone: "Sarikei, Matu, Julau, Rajang, Daro, Bintangor, Belawai", state: "Sarawak" },
      { code: "SWK06", zone: "Lubok Antu, Sri Aman, Roban, Debak, Kabong, Lingga, Engkelili, Betong, Spaoh, Pusa, Saratok", state: "Sarawak" },
      { code: "SWK07", zone: "Serian, Simunjan, Samarahan, Sebuyau, Meludam", state: "Sarawak" },
      { code: "SWK08", zone: "Kuching, Bau, Lundu, Sematan", state: "Sarawak" },
      { code: "SWK09", zone: "Zon Khas (Kampung Patarikan)", state: "Sarawak" },
      { code: "TRG01", zone: "Kuala Terengganu, Marang, Kuala Nerus", state: "Terengganu" },
      { code: "TRG02", zone: "Besut, Setiu", state: "Terengganu" },
      { code: "TRG03", zone: "Hulu Terengganu", state: "Terengganu" },
      { code: "TRG04", zone: "Dungun, Kemaman", state: "Terengganu" },
      { code: "WLY01", zone: "Kuala Lumpur, Putrajaya", state: "Wilayah Persekutuan" },
      { code: "WLY02", zone: "Labuan", state: "Wilayah Persekutuan" }
    ].map(&:stringify_keys)
  end
end
